### ISSUE TITLE
Fellow high schooler

### ISSUE THREAD

**Issue by hashgupta** [kjaisingh/high-school-guide-to-machine-learning#1]
Hey, nice to see a fellow high schooler in AI. I thought this project was really cool. I didn't check yet, but did you include the Coding Train, a series of programming videos by an college professor. Also, three blue one brown has some fantastic videos on deep learning and the math behind it. You can find but channels on youtube. 👍

**Comment by Omar-Elrefaei** [comment]
+1 for three blue one brown, his stuff is fascinating

**Comment by kjaisingh** [comment]
Thanks! I just added his videos into the guide, as I myself have learnt a great deal from them. I will check out Coding Train soon too!
