### ISSUE TITLE
Michael Nielsen's book should be included

### ISSUE THREAD

**Issue by Genarito** [kjaisingh/high-school-guide-to-machine-learning#3]
In my opinion, It would be nice that [Michael Nielsen's book](http://neuralnetworksanddeeplearning.com/chap1.html) was included in the list as It's a good introduction to Sigmoid Function, Cost Function (cuadratic, cross entropy, etc), Regularization (L1, L2, Dropout), CNN, Deep Learning, and much more. Also there is a Youtube Channel that make a lot of [videos](https://www.youtube.com/watch?v=aircAruvnKk) referencing that book with animations which helps to undestand better the concepts.

**Comment by kjaisingh** [comment]
Thank you for this! I have just included 3Blue1Brown's videos in the guide, as they are great.
